#    MagentoXMLRPCStub
#    Copyright (C) 2011 Guewen Baconnier
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'logger'
require 'xmlrpc/server'
require 'pp'

require 'app/base/base_model'
require 'app/api_base_models/catalog_product'
require 'app/api_base_models/sales_order'


module MagentoXMLRPCStub
  class Server
    attr_accessor :data
    attr_reader :xmlrpc_server

    def initialize(data)
      @data = data
      @log = Logger.new($stdout)

      @xmlrpc_server = XMLRPC::Server.new

      @xmlrpc_server.add_handler('login') do |login, password|
        @log.info "Logged with user #{login} and password #{password}"
        true
      end

      @xmlrpc_server.add_handler('call') do |session, model_method, *args|
        @log.info "Called method #{model_method}"
        call(model_method, *args)
      end
#
#      BaseModel.model_classes.each do |class_model|
#        @xmlrpc_server.add_handler(class_model.model_name, class_model.new(@log, @data[class_model.model_name]))
#      end

      # TODO add a config file for custom models and add handlers for them too

      @xmlrpc_server.set_default_handler do |name, *args|
        raise XMLRPC::FaultException.new(-99, "Method #{name} missing" +
                                         " or wrong number of parameters!")
      end
    end

    def call(model_method, *args)
      model, method = model_method.split('.')
      class_model = BaseModel.class_for(model)
      # TODO use singleton ?
      instance_model = class_model.new(@log, @data[class_model.model_name])
      instance_model.send(method.to_sym, *args)
    end

    def parse_file(parse_type='yaml')
      # set data from a file
      raise NotImplementedError
    end

    def run
      @xmlrpc_server.serve
      @xmlrpc_server.mount("index.php/api/xmlrpc/", @xmlrpc_server)
    end
  end
end


test_orders = {'100009493' => {
    "base_cod_tax_amount" => false,
    "discount_invoiced" => false,
    "shipping_address_id" => "17392",
    "base_shipping_refunded" => false,
    "base_subtotal_refunded" => false,
    "hold_before_status" => false,
    "base_total_online_refunded" => false,
    "base_tax_canceled" => false,
    "payment_authorization_expiration" => false,
    "tax_invoiced" => false,
    "shipping_discount_amount" => "0.0000",
    "payment" => {
        "cc_owner" => "",
        "cc_last4" => "",
        "base_amount_ordered" => "1373.0100",
        "shipping_amount" => "0.0000",
        "quote_payment_id" => false,
        "amount_refunded" => false,
        "base_shipping_captured" => false,
        "additional_information" => [],
        "cc_secure_verify" => false,
        "amount_canceled" => false,t
        "echeck_account_name" => false,
        "cc_debug_response_body" => false,
        "cc_ss_start_month" => "0",
        "cc_debug_response_serialized" => false,
        "cybersource_token" => false,
        "method" => "checkmo",
        "echeck_type" => false,
        "cc_approval" => false,
        "cc_exp_month" => "0",
        "base_shipping_refunded" => false,
        "amount_authorized" => false,
        "base_amount_refunded_online" => false,
        "base_amount_paid_online" => false,
        "shipping_captured" => false,
        "cc_ss_issue" => false,
        "cc_status_description" => false,
        "base_amount_paid" => false,
        "account_status" => false,
        "ideal_issuer_title" => false,
        "cc_ss_start_year" => "0",
        "address_status" => false,
        "flo2cash_account_id" => false,
        "cc_number_enc" => "",
        "cc_avs_status" => false,
        "anet_trans_method" => false,
        "cc_type" => "",
        "cc_cid_status" => false,
        "base_amount_canceled" => false,
        "base_amount_refunded" => false,
        "base_shipping_amount" => "0.0000",
        "parent_id" => "8696",
        "cc_trans_id" => false,
        "echeck_routing_number" => false,
        "paybox_question_number" => false,
        "additional_data" => "a:2:{s:10:\"payable_to\";s:8:\"Debonix \";s:15:\"mailing_address\";s:136:\"Merci d'envoyer votre ch\303\250que libell\303\251 \303\240 l'ordre de Debonix \303\240 l'adresse:\nDebonix\nService Commande\n158 rue de l'artisanat \n74330 Epagny\";}",
        "amount_ordered" => "1373.0100",
        "shipping_refunded" => false,
        "payment_id" => "8696",
        "po_number" => "",
        "last_trans_id" => false,
        "protection_eligibility" => false,
        "cc_debug_request_body" => false,
        "echeck_bank_name" => false,
        "base_amount_authorized" => false,
        "paybox_request_number" => false,
        "cc_status" => false,
        "cc_exp_year" => "0",
        "ideal_issuer_id" => false,
        "echeck_account_type" => false,
        "ideal_transaction_checked" => false,
        "amount_paid" => false
    },
    "base_subtotal_incl_tax" => "1373.0100",
    "base_discount_canceled" => false,
    "tax_amount" => "225.0100",
    "customer_email" => "naive@naivegraphics.net",
    "can_ship_partially_item" => false,
    "base_tax_invoiced" => false,
    "customer_middlename" => false,
    "ext_order_id" => false,
    "items" => [
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "498.7300",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:33",
            "sku" => "574375P",
            "price_incl_tax" => "498.7300",
            "base_price" => "417.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => false,
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "498.7300",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "417.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "417.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51910",
            "parent_item_id" => false,
            "base_discount_amount" => "0.0000",
            "weight" => "0.0000",
            "qty_shipped" => "0.0000",
            "has_children" => true,
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "329.6600",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "417.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:33",
            "name" => "D\303\251fonceuse OF1010 EBQ-Set FESTOOL + coffret de 66 fraises ISOCELE 574375P",
            "base_tax_amount" => "81.7300",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "81.7300",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "0.0000",
            "hidden_tax_invoiced" => false,
            "product_id" => "24730",
            "base_price_incl_tax" => "498.7300",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "417.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:228:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9kZWZvbmNldXNlL2RlZm9uY2V1c2Utb2YxMDEwLWVicS1zZXQtZmVzdG9vbC1jb2ZmcmV0LWRlLTY2LWZyYWlzZXMtaXNvY2VsZS01NzQzNzVwLmh0bWw,\";s:7:\"product\";s:5:\"24730\";s:15:\"related_product\";s:0:\"\";s:3:\"qty\";s:1:\"1\";}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21016",
            "original_price" => "417.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "874.2800",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:35",
            "sku" => "574427",
            "price_incl_tax" => "874.2800",
            "base_price" => "731.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "874.2800",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "731.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "731.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51911",
            "parent_item_id" => false,
            "base_discount_amount" => "0.0000",
            "weight" => "3.2000",
            "qty_shipped" => "0.0000",
            "has_children" => true,
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "496.2800",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "731.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:35",
            "name" => "Fraiseuse DOMINO DF 500 Q-Set, 420W  FESTOOL 574427",
            "base_tax_amount" => "143.2800",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "143.2800",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "3.2000",
            "hidden_tax_invoiced" => false,
            "product_id" => "20829",
            "base_price_incl_tax" => "874.2800",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "731.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:164:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9mcmFpc2V1c2UtYm9pcy1hLWxhbWVsbGVzLmh0bWw_bGltaXQ9MzA,\";s:7:\"product\";s:5:\"20829\";s:15:\"related_product\";s:5:\"11032\";s:3:\"qty\";i:1;}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21017",
            "original_price" => "731.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:37",
            "sku" => "494938",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => "CADEAU",
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51912",
            "parent_item_id" => false,
            "base_discount_amount" => "0.0000",
            "weight" => "0.0000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "7.0000",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:37",
            "name" => "Tenons DOMINO en h\303\252tre D 5X30/300 BU FESTOOL 494938",
            "base_tax_amount" => "0.0000",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "0.0000",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "0.0000",
            "hidden_tax_invoiced" => false,
            "product_id" => "11032",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:1:{s:15:\"info_buyRequest\";a:1:{s:3:\"qty\";i:1;}}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21018",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:33",
            "sku" => "574335",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => false,
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51910",
            "parent_item_id" => "21016",
            "base_discount_amount" => "0.0000",
            "weight" => "0.0000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "329.6600",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:33",
            "name" => "D\303\251fonceuse OF 1010 EBQ-Plus FESTOOL 574335(produit du pack : D\303\251fonceuse OF1010 EBQ-Set FESTOOL + coffret de 66 fraises ISOCELE 574375P)",
            "base_tax_amount" => "81.7300",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "81.7300",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "0.0000",
            "hidden_tax_invoiced" => false,
            "product_id" => "16709",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:228:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9kZWZvbmNldXNlL2RlZm9uY2V1c2Utb2YxMDEwLWVicS1zZXQtZmVzdG9vbC1jb2ZmcmV0LWRlLTY2LWZyYWlzZXMtaXNvY2VsZS01NzQzNzVwLmh0bWw,\";s:7:\"product\";s:5:\"24730\";s:15:\"related_product\";s:0:\"\";s:3:\"qty\";s:1:\"1\";}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21179",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:33",
            "sku" => "491499",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => false,
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51910",
            "parent_item_id" => "21016",
            "base_discount_amount" => "0.0000",
            "weight" => "0.0000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "329.6600",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:33",
            "name" => "Rail de guidage FS 800/2 FESTOOL 491499(produit du pack : D\303\251fonceuse OF1010 EBQ-Set FESTOOL + coffret de 66 fraises ISOCELE 574375P)",
            "base_tax_amount" => "81.7300",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "81.7300",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "0.0000",
            "hidden_tax_invoiced" => false,
            "product_id" => "10441",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:228:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9kZWZvbmNldXNlL2RlZm9uY2V1c2Utb2YxMDEwLWVicS1zZXQtZmVzdG9vbC1jb2ZmcmV0LWRlLTY2LWZyYWlzZXMtaXNvY2VsZS01NzQzNzVwLmh0bWw,\";s:7:\"product\";s:5:\"24730\";s:15:\"related_product\";s:0:\"\";s:3:\"qty\";s:1:\"1\";}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21180",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:33",
            "sku" => "428.700.66",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => false,
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51910",
            "parent_item_id" => "21016",
            "base_discount_amount" => "0.0000",
            "weight" => "0.0000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "329.6600",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:33",
            "name" => "Coffret de 66 m\303\250ches de d\303\251fonceuse Isocele 428.700.66(produit du pack : D\303\251fonceuse OF1010 EBQ-Set FESTOOL + coffret de 66 fraises ISOCELE 574375P)",
            "base_tax_amount" => "81.7300",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "81.7300",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "0.0000",
            "hidden_tax_invoiced" => false,
            "product_id" => "13147",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:228:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9kZWZvbmNldXNlL2RlZm9uY2V1c2Utb2YxMDEwLWVicS1zZXQtZmVzdG9vbC1jb2ZmcmV0LWRlLTY2LWZyYWlzZXMtaXNvY2VsZS01NzQzNzVwLmh0bWw,\";s:7:\"product\";s:5:\"24730\";s:15:\"related_product\";s:0:\"\";s:3:\"qty\";s:1:\"1\";}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21181",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:35",
            "sku" => "574325",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51911",
            "parent_item_id" => "21017",
            "base_discount_amount" => "0.0000",
            "weight" => "3.2000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "496.2800",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:35",
            "name" => "Fraiseuse Domino Df 500 Q-plus, 420W  Festool 574325(produit du pack : Fraiseuse DOMINO DF 500 Q-Set, 420W  FESTOOL 574427)",
            "base_tax_amount" => "143.2800",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "143.2800",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "3.2000",
            "hidden_tax_invoiced" => false,
            "product_id" => "15335",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:164:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9mcmFpc2V1c2UtYm9pcy1hLWxhbWVsbGVzLmh0bWw_bGltaXQ9MzA,\";s:7:\"product\";s:5:\"20829\";s:15:\"related_product\";s:5:\"11032\";s:3:\"qty\";i:1;}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21182",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:35",
            "sku" => "494847",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51911",
            "parent_item_id" => "21017",
            "base_discount_amount" => "0.0000",
            "weight" => "3.2000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "496.2800",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:35",
            "name" => "But\303\251e pour pi\303\250ces arrondies RA DF 500 FESTOOL 494847(produit du pack : Fraiseuse DOMINO DF 500 Q-Set, 420W  FESTOOL 574427)",
            "base_tax_amount" => "143.2800",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "143.2800",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "3.2000",
            "hidden_tax_invoiced" => false,
            "product_id" => "11590",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:164:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9mcmFpc2V1c2UtYm9pcy1hLWxhbWVsbGVzLmh0bWw_bGltaXQ9MzA,\";s:7:\"product\";s:5:\"20829\";s:15:\"related_product\";s:5:\"11032\";s:3:\"qty\";i:1;}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21183",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:35",
            "sku" => "493488",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51911",
            "parent_item_id" => "21017",
            "base_discount_amount" => "0.0000",
            "weight" => "3.2000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "496.2800",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:35",
            "name" => "But\303\251e QA-DF 500 FESTOOL 493488(produit du pack : Fraiseuse DOMINO DF 500 Q-Set, 420W  FESTOOL 574427)",
            "base_tax_amount" => "143.2800",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "143.2800",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "3.2000",
            "hidden_tax_invoiced" => false,
            "product_id" => "11591",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:164:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9mcmFpc2V1c2UtYm9pcy1hLWxhbWVsbGVzLmh0bWw_bGltaXQ9MzA,\";s:7:\"product\";s:5:\"20829\";s:15:\"related_product\";s:5:\"11032\";s:3:\"qty\";i:1;}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21184",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        },
        {
            "pix_ligne_id" => false,
            "row_total_incl_tax" => "0.0000",
            "qty_ordered" => "1.0000",
            "base_weee_tax_applied_row_amount" => "0.0000",
            "created_at" => "2011-06-14 10:40:35",
            "sku" => "493487",
            "price_incl_tax" => "0.0000",
            "base_price" => "0.0000",
            "base_hidden_tax_refunded" => false,
            "qty_backordered" => "1.0000",
            "base_tax_invoiced" => "0.0000",
            "tax_invoiced" => "0.0000",
            "base_row_total_incl_tax" => "0.0000",
            "is_qty_decimal" => "0",
            "description" => false,
            "order_id" => "8696",
            "base_original_price" => "0.0000",
            "weee_tax_disposition" => "0.0000",
            "tax_percent" => "19.6000",
            "gift_message_available" => "2",
            "price" => "0.0000",
            "ext_order_item_id" => false,
            "quote_item_id" => "51911",
            "parent_item_id" => "21017",
            "base_discount_amount" => "0.0000",
            "weight" => "3.2000",
            "qty_shipped" => "0.0000",
            "is_virtual" => "0",
            "marketplace_item_id" => false,
            "hidden_tax_refunded" => false,
            "base_cost" => "496.2800",
            "base_amount_refunded" => "0.0000",
            "applied_rule_ids" => "",
            "qty_refunded" => "0.0000",
            "product_type" => "simple",
            "row_total" => "0.0000",
            "is_nominal" => "0",
            "base_tax_before_discount" => false,
            "no_discount" => "0",
            "updated_at" => "2011-06-14 10:40:35",
            "name" => "But\303\251e LA-DF 500 FESTOOL 493487(produit du pack : Fraiseuse DOMINO DF 500 Q-Set, 420W  FESTOOL 574427)",
            "base_tax_amount" => "143.2800",
            "weee_tax_applied" => "a:0:{}",
            "tax_amount" => "143.2800",
            "discount_amount" => "0.0000",
            "weee_tax_applied_amount" => "0.0000",
            "base_hidden_tax_invoiced" => false,
            "additional_data" => false,
            "row_weight" => "3.2000",
            "hidden_tax_invoiced" => false,
            "product_id" => "11592",
            "base_price_incl_tax" => "0.0000",
            "base_weee_tax_applied_amount" => "0.0000",
            "locked_do_ship" => false,
            "weee_tax_row_disposition" => "0.0000",
            "discount_percent" => "0.0000",
            "base_hidden_tax_amount" => "0.0000",
            "base_row_total" => "0.0000",
            "weee_tax_applied_row_amount" => "0.0000",
            "store_id" => "1",
            "tax_before_discount" => false,
            "locked_do_invoice" => false,
            "base_discount_invoiced" => "0.0000",
            "base_weee_tax_row_disposition" => "0.0000",
            "discount_invoiced" => "0.0000",
            "qty_invoiced" => "0.0000",
            "base_weee_tax_disposition" => "0.0000",
            "hidden_tax_amount" => "0.0000",
            "row_invoiced" => "0.0000",
            "product_options" => "a:3:{s:15:\"info_buyRequest\";a:4:{s:4:\"uenc\";s:164:\"aHR0cDovL3d3dy5kZWJvbml4LmZyL291dGlsbGFnZS1lbGVjdHJvcG9ydGF0aWYvZnJhaXNldXNlLWFmZmxldXJldXNlLWRlZm9uY2V1c2UtMy9mcmFpc2V1c2UtYm9pcy1hLWxhbWVsbGVzLmh0bWw_bGltaXQ9MzA,\";s:7:\"product\";s:5:\"20829\";s:15:\"related_product\";s:5:\"11032\";s:3:\"qty\";i:1;}s:13:\"shipment_type\";i:1;s:20:\"product_calculations\";i:0;}",
            "qty_canceled" => "0.0000",
            "amount_refunded" => "0.0000",
            "gift_message_id" => false,
            "item_id" => "21185",
            "original_price" => "0.0000",
            "free_shipping" => "0",
            "base_row_invoiced" => "0.0000"
        }
    ],
    "base_shipping_incl_tax" => "0.0000",
    "original_increment_id" => false,
    "base_adjustment_positive" => false,
    "hidden_tax_invoiced" => false,
    "base_shipping_tax_amount" => "0.0000",
    "base_subtotal_canceled" => false,
    "base_discount_refunded" => false,
    "subtotal_invoiced" => false,
    "total_online_refunded" => false,
    "order_currency_code" => "EUR",
    "rdc_validated" => "0",
    "customer_lastname" => "Bielefeldt",
    "marketplace_order_id" => false,
    "grand_total" => "1373.0100",
    "store_to_order_rate" => "1.0000",
    "cod_fee_invoiced" => false,
    "customer_gender" => false,
    "base_total_paid" => false,
    "base_cod_fee" => false,
    "base_hidden_tax_refunded" => false,
    "hidden_tax_amount" => "0.0000",
    "remote_ip" => "84.97.93.32",
    "forced_do_shipment_with_invoice" => false,
    "paypal_ipn_customer_notified" => false,
    "base_adjustment_negative" => false,
    "adjustment_positive" => false,
    "ext_customer_id" => false,
    "created_at" => "2011-06-14 10:40:33",
    "base_total_due" => false,
    "shipping_amount" => "0.0000",
    "base_discount_invoiced" => false,
    "base_currency_code" => "EUR",
    "can_ship_partially" => false,
    "base_shipping_discount_amount" => "0.0000",
    "base_total_refunded" => false,
    "order_id" => "8696",
    "discount_amount" => "0.0000",
    "base_shipping_canceled" => false,
    "cod_tax_amount" => false,
    "relation_parent_real_id" => false,
    "subtotal" => "1148.0000",
    "rdc_canceled" => "0",
    "hold_before_state" => false,
    "relation_parent_id" => false,
    "billing_address_id" => "17391",
    "hidden_tax_refunded" => false,
    "base_hidden_tax_invoiced" => false,
    "customer_suffix" => false,
    "base_total_canceled" => false,
    "base_subtotal_invoiced" => false,
    "pix_order_id" => false,
    "base_to_global_rate" => "1.0000",
    "adjustment_negative" => false,
    "customer_id" => "26411",
    "shipping_tax_amount" => "0.0000",
    "onestepcheckout_customercomment" => false,
    "weight" => "3.2000",
    "base_total_invoiced_cost" => false,
    "base_hidden_tax_amount" => "0.0000",
    "edit_increment" => false,
    "is_virtual" => "0",
    "customer_is_guest" => "0",
    "customer_firstname" => "Ivan",
    "base_shipping_tax_refunded" => false,
    "fianet_rnp_tag" => false,
    "gift_message_id" => false,
    "customer_prefix" => false,
    "billing_address" => {
        "company" => "",
        "city" => "Carri\303\250res sur Seine",
        "region" => "Yvelines",
        "customer_address_id" => false,
        "prefix" => false,
        "postcode" => "78420",
        "middlename" => false,
        "country_id" => "FR",
        "street" => "15bis rue du Moulin",
        "lastname" => "Bielefeldt",
        "address_id" => "17391",
        "region_id" => "260",
        "address_type" => "billing",
        "firstname" => "Ivan",
        "fax" => "",
        "parent_id" => "8696",
        "suffix" => false,
        "telephone" => "0672728512",
        "customer_id" => "26411",
        "quote_address_id" => false,
        "email" => false
    },
    "rdc" => "0",
    "pix_ligne_id" => false,
    "cod_tax_amount_invoiced" => false,
    "onestepcheckout_customerfeedback" => false,
    "base_shipping_hidden_tax_amount" => "0.0000",
    "base_shipping_amount" => "0.0000",
    "total_paid" => false,
    "total_due" => false,
    "shipping_tax_refunded" => false,
    "payment_authorization_amount" => false,
    "base_tax_refunded" => false,
    "x_forwarded_for" => "84.97.93.32",
    "base_tax_amount" => "225.0100",
    "quote_address_id" => false,
    "status" => "pending",
    "updated_at" => "2011-06-14 10:40:39",
    "base_shipping_invoiced" => false,
    "shipping_description" => "Chronopost -  Frais de port offerts - Chronopost",
    "discount_description" => "",
    "fianet_rnp_mode" => false,
    "base_cod_tax_amount_invoiced" => false,
    "total_item_count" => "3",
    "tax_canceled" => false,
    "coupon_code" => "",
    "total_refunded" => false,
    "store_to_base_rate" => "1.0000",
    "from_site" => false,
    "rdc_order_id" => false,
    "relation_child_id" => false,
    "global_currency_code" => "EUR",
    "base_cod_fee_invoiced" => false,
    "shipping_incl_tax" => "0.0000",
    "store_name" => "Main Website\nMain Website Store\nDefault Store View",
    "tax_refunded" => false,
    "base_total_invoiced" => false,
    "email_sent" => "1",
    "total_qty_ordered" => "3.0000",
    "protect_code" => "3abee7",
    "customer_group_id" => "1",
    "quote_id" => "26665",
    "relation_child_real_id" => false,
    "total_canceled" => false,
    "base_total_offline_refunded" => false,
    "increment_id" => "100009493",
    "shipping_canceled" => false,
    "shipping_method" => "owebiashipping2_chronopost_offert",
    "customer_dob" => false,
    "subtotal_refunded" => false,
    "shipping_address" => {
        "company" => "",
        "city" => "Carri\303\250res sur Seine",
        "region" => "Yvelines",
        "customer_address_id" => "26933",
        "prefix" => false,
        "postcode" => "78420",
        "middlename" => false,
        "country_id" => "FR",
        "street" => "15bis rue du Moulin",
        "lastname" => "Bielefeldt",
        "address_id" => "17392",
        "region_id" => "260",
        "address_type" => "shipping",
        "firstname" => "Ivan",
        "fax" => "",
        "parent_id" => "8696",
        "suffix" => false,
        "telephone" => "0672728512",
        "customer_id" => "26411",
        "quote_address_id" => false,
        "email" => false
    },
    "pix_refunded" => "0",
    "pix_validated" => "0",
    "pix" => "0",
    "shipping_refunded" => false,
    "customer_note_notify" => "1",
    "shipping_hidden_tax_amount" => "0.0000",
    "subtotal_incl_tax" => "1373.0100",
    "discount_canceled" => false,
    "base_subtotal" => "1148.0000",
    "rdc_tracking_code_sent" => "0",
    "customer_note" => false,
    "base_to_order_rate" => "1.0000",
    "subtotal_canceled" => false,
    "discount_refunded" => false,
    "total_offline_refunded" => false,
    "marketplace_name" => false,
    "state" => "new",
    "customer_taxvat" => false,
    "status_history" => [
        {
            "comment" => false,
            "created_at" => "2011-06-14 10:40:39",
            "is_visible_on_front" => "0",
            "store_id" => "1",
            "parent_id" => "8696",
            "is_customer_notified" => "1",
            "status" => "pending"
        }
    ],
    "base_grand_total" => "1373.0100",
    "fianet_rnp_tag_mode" => false,
    "cod_fee" => false,
    "store_id" => "1",
    "total_invoiced" => false,
    "base_total_qty_ordered" => false,
    "applied_rule_ids" => "",
    "shipping_invoiced" => false,
    "store_currency_code" => "EUR",
    "base_discount_amount" => "0.0000"
}
}

# Test stuff
server = MagentoXMLRPCStub::Server.new(
    {'catalog_product' => {
        [1, 'SKU1'] =>
            {'name' => 'Product 1',
             'price' => 10.0}
    },
     'sales_order' => test_orders
    }
)

server.run

#require 'xmlrpc/client'
#require 'pp'
#class XMLRPC::Client
#  def set_debug
#    @http.set_debug_output($stderr);
#  end
#end
#server = XMLRPC::Client.new("127.0.0.1", "/index.php/api/xmlrpc/", 8080)
#server.set_debug
#pp server.call("sales_order.info", '100009493')